### ISSUE TITLE
Update uniswap.ninja with the new version.

### ISSUE THREAD

**Issue by clesaege** [kleros/uniswap-frontend#11]

**Comment by eccentricexit** [comment]
Implemented in commits [3454d4](https://github.com/kleros/uniswap-frontend/commit/3454d4d7fcb713eff84cc044ec44e0c5d450bf94), [db84e0](https://github.com/kleros/uniswap-frontend/commit/db84e033a1e4d60ecfdb3a0fb1fdc7769c57937d), [7187e5](https://github.com/kleros/uniswap-frontend/commit/7187e567a71456cab2af5fbd21f90f20dec3e751) and [d90625](https://github.com/kleros/uniswap-frontend/commit/d90625714d03f6494566300cd3a6e3797961944b)

**Comment by clesaege** [comment]
A few quick things to match uniswap.exchange:
- The ticker is given first
- The name is given in greyscale
- Logos are larger
