### ISSUE TITLE
Update loading speed of the token list.

### ISSUE THREAD

**Issue by clesaege** [kleros/uniswap-frontend#12]
Loading of tokens takes way too much time on https://uniswap.ninja/swap and https://escrow.kleros.io/new/payment to be able to have partner use this list.
We need a way to reduce loading time.

**Comment by eccentricexit** [comment]
Token list loading on uniswap was sped up by using caching on commit [cc73b7](cc73b7da589ce3b83896299445117b04c08f3ccc).

I opened the same issue on the [escrow repository](https://github.com/kleros/escrow/issues/54)
